language: node_js
node_js:
  - 7
  - 8
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn build
